apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wr6sntykm-python 
  janus-idp.io/tekton: wr6sntykm-python
  backstage.io/kubernetes-id: wr6sntykm-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wr6sntykm-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml