apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wr6sntykm-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wr6sntykm-python 
  name: wr6sntykm-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: wr6sntykm-python 
